name: Test

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.23.0
        with:
          api-level: 31
          target: playstore
          arch: x86_64
          script: ./gradlew connectedCheck --exclude-task json:test --exclude-task app:processDebugGoogleServices --exclude-task app:processReleaseGoogleServices